version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Isadg002
    ports:
      - "5005:1433" 
    volumes:
      - mssql-data:/var/opt/mssql 

volumes:
  mssql-data:
