version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    ports:
      - 5004:9000
      - 5005:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  data: